Another attempt to fix workflow

diff --git a/.github/workflows/msbuild.yml b/.github/workflows/msbuild.yml
--- a/.github/workflows/msbuild.yml
+++ b/.github/workflows/msbuild.yml
@@ -43,6 +43,10 @@ jobs:
       working-directory: ${{env.GITHUB_WORKSPACE}}
       timeout-minutes: 1
       run: |
+        if exist Projects\Pong\Assets\Scripting\Binary (
+          echo "Removing cached scripting binaries"
+          rmdir /s /q Projects\Pong\Assets\Scripting\Binary || echo "Failed to remove cached scripting binaries"
+        )
         cd Binary\${{matrix.build-configuration}}-windows-x86_64\RuntimeTesting
         RuntimeTesting.exe
     - name: TestEditor
