Add ServerTesting into test suite and added stop server - Fixed server always crashing when closed - Added ServerTesting project to Testing directory - Added ServerTesting into msbuild.yml workflow

diff --git a/.github/workflows/msbuild.yml b/.github/workflows/msbuild.yml
--- a/.github/workflows/msbuild.yml
+++ b/.github/workflows/msbuild.yml
@@ -61,18 +61,35 @@ jobs:
         )
         cd Binary\${{matrix.build-configuration}}-windows-x86_64\EditorTesting
         EditorTesting.exe
+    - name: TestServer
+      if: ${{ always() }}
+      shell: cmd
+      working-directory: ${{env.GITHUB_WORKSPACE}}
+      timeout-minutes: 1
+      run: |
+        if exist Projects\Pong\Assets\Scripting\Binary (
+          echo "Removing cached scripting binaries"
+          rmdir /s /q Projects\Pong\Assets\Scripting\Binary || echo "Failed to remove cached scripting binaries"
+        )
+        cd Binary\${{matrix.build-configuration}}-windows-x86_64\ServerTesting
+        ServerTesting.exe
     - name: Display Logs
       if: ${{ always() }}
       shell: cmd
       run: |
         if exist Runtime/Log/Kargono.log (
-          echo "Here is the log for the TestRuntime Step" && type Runtime\Log\Kargono.log || echo "Failed to write Kargono.log out to the console"
+          echo "Here is the log for the TestRuntime Step" && type Runtime\Log\Kargono.log || echo "Failed to write Runtime Kargono.log out to the console"
         ) else (
           echo "Runtime log file does not exist"
         )
         if exist Editor/Log/Kargono.log (
-          echo "Here is the log for the EditorRuntime Step" && type Editor\Log\Kargono.log || echo "Failed to write Kargono.log out to the console"
+          echo "Here is the log for the EditorRuntime Step" && type Editor\Log\Kargono.log || echo "Failed to write Editor Kargono.log out to the console"
         ) else (
           echo "Editor log file does not exist"
+        )
+        if exist Server/Log/Kargono.log (
+          echo "Here is the log for the ServerRuntime Step" && type Server\Log\Kargono.log || echo "Failed to write Server Kargono.log out to the console"
+        ) else (
+          echo "Server log file does not exist"
         )
         exit 0
