Another attempt to fix workflow issues

diff --git a/.github/workflows/msbuild.yml b/.github/workflows/msbuild.yml
--- a/.github/workflows/msbuild.yml
+++ b/.github/workflows/msbuild.yml
@@ -42,20 +42,22 @@ jobs:
       shell: cmd
       working-directory: ${{env.GITHUB_WORKSPACE}}
       timeout-minutes: 1
-      run: | 
+      run: |
         if exist Projects\Pong\Assets\Scripting\Binary (
-          echo "Removing cached scripting binaries" && rmdir /s /q Projects\Pong\Assets\Scripting\Binary || echo "Failed to remove cached scripting binaries"
-        ) 
+          echo "Removing cached scripting binaries"
+          rmdir /s /q Projects\Pong\Assets\Scripting\Binary || echo "Failed to remove cached scripting binaries"
+        )
         Binary\${{matrix.build-configuration}}-windows-x86_64\RuntimeTesting\RuntimeTesting.exe
     - name: TestEditor
       if: ${{ always() }}
       shell: cmd
       working-directory: ${{env.GITHUB_WORKSPACE}}
       timeout-minutes: 1
-      run: | 
+      run: |
         if exist Projects\Pong\Assets\Scripting\Binary (
-          echo "Removing cached scripting binaries" && rmdir /s /q Projects\Pong\Assets\Scripting\Binary || echo "Failed to remove cached scripting binaries"
-        ) 
+          echo "Removing cached scripting binaries"
+          rmdir /s /q Projects\Pong\Assets\Scripting\Binary || echo "Failed to remove cached scripting binaries"
+        )
         Binary\${{matrix.build-configuration}}-windows-x86_64\EditorTesting\EditorTesting.exe
     - name: Display Logs
       if: ${{ always() }}
