Fix compilation issues - Move editor workflow to top in msbuild.yml - Generate TestProject in EditorTesting, which is then used in RuntimeTesting and ServerTesting - Fix AIService compilation issues

diff --git a/.github/workflows/msbuild.yml b/.github/workflows/msbuild.yml
--- a/.github/workflows/msbuild.yml
+++ b/.github/workflows/msbuild.yml
@@ -37,18 +37,6 @@ jobs:
       # Add additional options to the MSBuild command line here (like platform or verbosity level).
       # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
       run: msbuild /m /p:Configuration=${{matrix.build-configuration}} ${{env.SOLUTION_FILE_PATH}}
-    - name: TestRuntime
-      if: ${{ always() }}
-      shell: cmd
-      working-directory: ${{env.GITHUB_WORKSPACE}}
-      timeout-minutes: 1
-      run: |
-        if exist Projects\Pong\Assets\Scripting\Binary (
-          echo "Removing cached scripting binaries"
-          rmdir /s /q Projects\Pong\Assets\Scripting\Binary || echo "Failed to remove cached scripting binaries"
-        )
-        cd Binary\${{matrix.build-configuration}}_windows\RuntimeTesting
-        RuntimeTesting.exe
     - name: TestEditor
       if: ${{ always() }}
       shell: cmd
@@ -61,6 +49,18 @@ jobs:
         )
         cd Binary\${{matrix.build-configuration}}_windows\EditorTesting
         EditorTesting.exe
+    - name: TestRuntime
+      if: ${{ always() }}
+      shell: cmd
+      working-directory: ${{env.GITHUB_WORKSPACE}}
+      timeout-minutes: 1
+      run: |
+        if exist Projects\Pong\Assets\Scripting\Binary (
+          echo "Removing cached scripting binaries"
+          rmdir /s /q Projects\Pong\Assets\Scripting\Binary || echo "Failed to remove cached scripting binaries"
+        )
+        cd Binary\${{matrix.build-configuration}}_windows\RuntimeTesting
+        RuntimeTesting.exe
     - name: TestServer
       if: ${{ always() }}
       shell: cmd
@@ -77,15 +77,15 @@ jobs:
       if: ${{ always() }}
       shell: cmd
       run: |
-        if exist Runtime/Log/Kargono.log (
-          echo "Here is the log for the TestRuntime Step" && type Runtime\Log\Kargono.log || echo "Failed to write Runtime Kargono.log out to the console"
-        ) else (
-          echo "Runtime log file does not exist"
-        )
         if exist Editor/Log/Kargono.log (
           echo "Here is the log for the EditorRuntime Step" && type Editor\Log\Kargono.log || echo "Failed to write Editor Kargono.log out to the console"
         ) else (
           echo "Editor log file does not exist"
+        )
+        if exist Runtime/Log/Kargono.log (
+          echo "Here is the log for the TestRuntime Step" && type Runtime\Log\Kargono.log || echo "Failed to write Runtime Kargono.log out to the console"
+        ) else (
+          echo "Runtime log file does not exist"
         )
         if exist Server/Log/Kargono.log (
           echo "Here is the log for the ServerRuntime Step" && type Server\Log\Kargono.log || echo "Failed to write Server Kargono.log out to the console"
